name: Deploy Paginated Reports

on:
  push:
    branches:
      - main
    paths:
      - 'reports/**'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  deploy-non-prod:
    name: "Deploy to Non-Prod"
    runs-on: ubuntu-latest
    environment: non-prod

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Paginated Reports
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ./scripts/Deploy-PaginatedReports.ps1 -TenantId "${{ secrets.TENANT_ID }}" -AppId "${{ secrets.APP_ID_NON_PROD }}" -AppSecret "${{ secrets.APP_SECRET_NON_PROD }}" -Environment "non-prod"
          errorActionPreference: "stop"
          failOnStandardError: true

  deploy-prod:
    name: "Deploy to Prod"
    runs-on: ubuntu-latest
    needs: deploy-non-prod
    environment:
      name: prod
      url: your-prod-environment-url # Optional

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Paginated Reports
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ./scripts/Deploy-PaginatedReports.ps1 -TenantId "${{ secrets.TENANT_ID }}" -AppId "${{ secrets.APP_ID_PROD }}" -AppSecret "${{ secrets.APP_SECRET_PROD }}" -Environment "prod"
          errorActionPreference: "stop"
          failOnStandardError: true
